repos:
# Syntax check with pre-commit out-of-the-box hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
  - id: detect-private-key
  - id: requirements-txt-fixer
  - id: pretty-format-json
    args: [--autofix, --no-ensure-ascii, --no-sort-keys]

# Format YAML & TOML files prettily
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

# Remove unused imports, unused variables and duplicate-keys with autoflake
- repo: https://github.com/PyCQA/autoflake
  rev: v2.0.1
  hooks:
  - id: autoflake
    args:
    - --in-place
    - --remove-unused-variables
    - --remove-all-unused-imports
    - --remove-duplicate-keys

# Bring Python code up to date with pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

# Automatic source code formatting with Black
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

# Automatically sort imports with isort
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

# Autofix F541 f-string is missing placeholders
- repo: https://github.com/dannysepler/rm_unneeded_f_str
  rev: v0.2.0
  hooks:
  - id: rm-unneeded-f-str

# Enforce style with Flake8
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: [Flake8-pyproject]

# Static type checker
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
  - id: mypy

# Find common security issues in Python with bandit
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  - id: bandit
    exclude: ^tests/.*\.py$
